FROM php:7.4-apache
RUN docker-php-ext-install mysqli


COPY 000-default.conf /etc/apache2/sites-available/000-default.conf
RUN mkdir /usr/local/env/
COPY start-apache /usr/local/bin
RUN a2enmod rewrite

# Copy application source
COPY . /var/www/
RUN chown -R www-data:www-data /var/www

CMD ["/bin/sh","./../start-apache"]