# Make sure it matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.1.3
FROM ruby:$RUBY_VERSION
RUN gem install bundler -v 2.3.26

EXPOSE 3000
EXPOSE 9995

ADD . /code
WORKDIR /code
RUN bundle install

CMD ["ruby","bin/rails", "server","-b","0.0.0.0"]